"Resource/UI/Customizations/#Customization_Menu/hud_customization_dev.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_Dev_Selection"
			{
				"controlName"							"CScrollableList"
				"fieldName"								"HUD_Dev_Selection"
				"xpos"									"cs-0.5"
				"ypos"									"cs-0.5"
				"zpos"									"0"
				"wide"									"f0"
				"tall"									"f0"
				"visible"								"0"
				"enabled"								"1"
				"proportionalToParent"					"1"
				"paintBackground"						"0"
				"paintBackgroundType"					"0"
				"BGColor_Override"						"Black"

				"Scrollbar"
				{
					"xpos"								"rs1+1"
					"ypos"								"0"
					"wide"								"6"
					"tall"								"f0"
					"zpos"								"1000"
					"proportionalToParent"				"1"

					"Slider"
					{
						"PaintBackgroundType"			"0"
						"FGColor_Override"				"Gray"
					}

					"nobuttons"							"1"
				}
				
				
				"Title_Icon"
				{
					"controlName"						"CExLabel"
					"fieldName"							"Title_Icon"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"20"
					"tall"								"25"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"labelText"							"v"
					"font"								"MediumIcons"
					"textAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Title"
				{
					"controlName"						"CExLabel"
					"fieldName"							"Title"
					"xpos"								"25"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"f25"
					"tall"								"25"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"labelText"							"IN-DEV"
					"font"								"HudFontMediumBold"
					"textAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_1"
				{
					"controlName"						"EditablePanel"
					"fieldName"							"Separator_1"
					"xpos"								"0"
					"ypos"								"30"
					"zpos"								"0"
					"wide"								"f40"
					"tall"								"2"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"1"
					"PaintBackgroundType"				"3"
					"BGColor_Override"					"Gray"
				}
				//==========================================================================================================
				// HEALTH & AMMO LAYOUT
				//==========================================================================================================
				"Layout_Options"
				{
					"controlName"						"EditablePanel"
					"fieldName"							"Layout_Options"
					"xpos"								"0"
					"ypos"								"36"
					"zpos"								"20"
					"wide"								"f0"
					"tall"								"75"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					
					"Layout_Icon"
					{
						"controlName"					"CExLabel"
						"fieldName"						"Layout_Icon"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"20"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionalToParent"			"1"
						"labelText"						"$"
						"font"							"MediumSmallIcons"
						"textAlignment"					"center"
						"FGColor"						"Gray"
					}
					"Layout_Title"
					{
						"controlName"					"CExLabel"
						"fieldName"						"Layout_Title"
						"xpos"							"3"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"f25"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionalToParent"			"1"
						"labelText"						"Layout"
						"font"							"HudFontSmallBold"
						"textAlignment"					"west"
						"FGColor"						"Gray"

						"pin_to_sibling"				"Layout_Icon"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"
					}
					"Separator_2"
					{
						"controlName"						"EditablePanel"
						"fieldName"							"Separator_2"
						"xpos"								"0"
						"ypos"								"5"
						"zpos"								"0"
						"wide"								"f40"
						"tall"								"1"
						"visible"							"1"
						"enabled"							"1"
						"proportionalToParent"				"1"
						"paintBackground"					"1"
						"PaintBackgroundType"				"3"
						"BGColor_Override"					"Gray"

						"pin_to_sibling"					"Layout_Icon"
						"pin_corner_to_sibling"				"PIN_TOPLEFT"
						"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"
					}
					//========================================================================================
					// CENTERED LAYOUT
					//========================================================================================
					"Style_Center"
					{
						"controlName"					"EditablePanel"
						"fieldName"						"Style_Center"
						"xpos"							"-3"
						"ypos"							"5"
						"zpos"							"1"
						"wide"							"120"
						"tall"							"50"
						"visible"						"1"
						"enabled"						"1"
						"proportionalToParent"			"1"
						"paintBackground"				"0"

						"pin_to_sibling"				"Separator_2"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"Style_Name"
						{
							"controlName"				"CExLabel"
							"fieldName"					"Style_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionalToParent"		"1"
							"font"						"FontStorePrice"
							"labelText"					"Centered"
							"textAlignment"				"center"
							"FGColor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Black"
						}
						"Size_Normal_Image"
						{
							"controlName"				"ImagePanel"
							"fieldName"					"Size_Normal_Image"
							"xpos"						"cs-0.5"
							"ypos"						"-4"
							"zpos"						"0"
							"wide"						"120"
							"tall"						"30"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionalToParent"		"1"
							"Image"						""
						}
						"Size_Button"
						{
							"controlName"				"CExButton"
							"fieldName"					"Size_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine hud_layout_clear"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionalToParent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"paintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"DarkBorderThick"
						}
					}
					//========================================================================================
					// CORNERED LAYOUT
					//========================================================================================
					"Style_Corner"
					{
						"controlName"					"EditablePanel"
						"fieldName"						"Style_Corner"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"120"
						"tall"							"50"
						"visible"						"1"
						"enabled"						"1"
						"proportionalToParent"			"1"
						"paintBackground"				"0"

						"pin_to_sibling"				"Style_Center"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Style_Name"
						{
							"controlName"				"CExLabel"
							"fieldName"					"Style_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionalToParent"		"1"
							"font"						"FontStorePrice"
							"labelText"					"Cornered"
							"textAlignment"				"center"
							"FGColor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Black"
						}
						"Size_Normal_Image"
						{
							"controlName"				"ImagePanel"
							"fieldName"					"Size_Normal_Image"
							"xpos"						"cs-0.5"
							"ypos"						"-4"
							"zpos"						"0"
							"wide"						"120"
							"tall"						"30"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionalToParent"		"1"
							"Image"						""
						}
						"Size_Button"
						{
							"controlName"				"CExButton"
							"fieldName"					"Size_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine hud_layout_cornered"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionalToParent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"paintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"DarkBorderThick"
						}
					}
				}
				//==========================================================================================================
				// SCOREBOARD
				//==========================================================================================================
				"Scoreboards_Icon"
				{
					"controlName"						"CExLabel"
					"fieldName"							"Scoreboards_Icon"
					"xpos"								"4"
					"ypos"								"386"
					"zpos"								"0"
					"wide"								"20"
					"tall"								"25"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"labelText"							"J"
					"font"								"MediumIcons"
					"textAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Scoreboard_Label"
				{
					"controlName"						"CExLabel"
					"fieldName"							"Scoreboard_Label"
					"xpos"								"32"
					"ypos"								"386"
					"zpos"								"0"
					"wide"								"f25"
					"tall"								"27"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"labelText"							"Scoreboard"
					"font"								"HudFontMediumbold"
					"textAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_7"
				{
					"controlName"						"EditablePanel"
					"fieldName"							"Separator_7"
					"xpos"								"3"
					"ypos"								"412"
					"zpos"								"0"
					"wide"								"f40"
					"tall"								"2"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"
					"paintBackground"					"1"
					"PaintBackgroundType"				"3"
					"BGColor_Override"					"Gray"
				}
				"Scoreboard_Styles"
				{
					"controlName"						"EditablePanel"
					"fieldName"							"Scoreboard_Styles"
					"xpos"								"4"
					"ypos"								"420"
					"zpos"								"20"
					"wide"								"250"
					"tall"								"110"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"

					"Style_Label"
					{
						"controlName"					"CExLabel"
						"fieldName"						"Style_Label"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"f25"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionalToParent"			"1"
						"labelText"						"Scoreboard Style"
						"font"							"HudFontSmallBold"
						"textAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"controlName"					"EditablePanel"
						"fieldName"						"Separator"
						"xpos"							"2"
						"ypos"							"1"
						"zpos"							"0"
						"wide"							"f15"
						"tall"							"1"
						"visible"						"1"
						"enabled"						"1"
						"proportionalToParent"			"1"
						"paintBackground"				"1"
						"PaintBackgroundType"			"3"
						"BGColor_Override"				"Gray"

						"pin_to_sibling"				"Style_Label"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
					"Scoreboard_Normal"
					{
						"controlName"					"EditablePanel"
						"fieldName"						"Scoreboard_Normal"
						"xpos"							"-2"
						"ypos"							"5"
						"zpos"							"1"
						"wide"							"120"
						"tall"							"82"
						"visible"						"1"
						"enabled"						"1"
						"proportionalToParent"			"1"
						"paintBackground"				"1"
						"BGColor_Override"				"104 101 100 255"

						"pin_to_sibling"				"Separator"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"Scoreboard_Image"
						{
							"controlName"				"ImagePanel"
							"fieldName"					"Scoreboard_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-6"
							"zpos"						"0"
							"wide"						"120"
							"tall"						"70"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionalToParent"		"1"
							"Image"						""
						}
						"Scoreboard_Label"
						{
							"controlName"				"CExLabel"
							"fieldName"					"Scoreboard_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionalToParent"		"1"
							"font"						"FontStorePrice"
							"labelText"					"Normal"
							"textAlignment"				"center"
							"FGColor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Black"
						}
						"Scoreboard_Button"
						{
							"controlName"				"CExButton"
							"fieldName"					"Scoreboard_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine hud_scoreboard_style_clear"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionalToParent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"paintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"DarkBorderThick"
						}
					}
					"Scoreboard_Fullscreen"
					{
						"controlName"					"EditablePanel"
						"fieldName"						"Scoreboard_Fullscreen"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"120"
						"tall"							"82"
						"visible"						"1"
						"enabled"						"1"
						"proportionalToParent"			"1"
						"paintBackground"				"1"
						"BGColor_Override"				"104 101 100 255"

						"pin_to_sibling"				"Scoreboard_Normal"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Scoreboard_Image"
						{
							"controlName"				"ImagePanel"
							"fieldName"					"Scoreboard_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-3"
							"zpos"						"0"
							"wide"						"130"
							"tall"						"130"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionalToParent"		"1"
							"Image"						""
						}
						"Scoreboard_Label"
						{
							"controlName"				"CExLabel"
							"fieldName"					"Scoreboard_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionalToParent"		"1"
							"font"						"FontStorePrice"
							"labelText"					"Fullscreen"
							"textAlignment"				"center"
							"FGColor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Black"
						}
						"Scoreboard_Button"
						{
							"controlName"				"CExButton"
							"fieldName"					"Scoreboard_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine hud_scoreboard_large"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionalToParent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"paintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"DarkBorderThick"
						}
					}
				}
				"Scoreboard_Settings"
				{
					"controlName"						"EditablePanel"
					"fieldName"							"Scoreboard_Settings"
					"xpos"								"266"
					"ypos"								"420"
					"zpos"								"20"
					"wide"								"160"
					"tall"								"70"
					"visible"							"1"
					"enabled"							"1"
					"proportionalToParent"				"1"

					"Settings_Label"
					{
						"controlName"					"CExLabel"
						"fieldName"						"Settings_Label"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"f25"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionalToParent"			"1"
						"labelText"						"Settings"
						"font"							"HudFontSmallBold"
						"textAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"controlName"					"EditablePanel"
						"fieldName"						"Separator"
						"xpos"							"2"
						"ypos"							"1"
						"zpos"							"0"
						"wide"							"f15"
						"tall"							"1"
						"visible"						"1"
						"enabled"						"1"
						"proportionalToParent"			"1"
						"paintBackground"				"1"
						"PaintBackgroundType"			"3"
						"BGColor_Override"				"Gray"

						"pin_to_sibling"				"Settings_Label"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
					"Scoreboard_Mouse_Input"
					{
						"controlName"					"EditablePanel"
						"fieldName"						"Scoreboard_Mouse_Input"
						"xpos"							"-2"
						"ypos"							"4"
						"zpos"							"1"
						"wide"							"130"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionalToParent"			"1"

						"pin_to_sibling"				"Separator"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"Toggle_Button"
						{
							"controlName"				"CExButton"
							"fieldName"					"Toggle_Button"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"20"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"actionsignallevel"			"6"
							"proportionalToParent"		"1"
							"paintbackground"			"0"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle tf_scoreboard_mouse_mode 0 2"
							"sound_depressed"			"UI/buttonclick.wav"
							"sound_released"			"UI/buttonclickrelease.wav"
						}
						"Setting_Checkbox"
						{
							"controlName"				"CvarToggleCheckButton"
							"fieldName"					"Setting_Checkbox"
							"xpos"						"-2"
							"ypos"						"cs-0.5"
							"zpos"						"21"
							"wide"						"f0"
							"tall"						"f0"
							"proportionalToParent"		"1"
							"font"						"ItemFontNameLarge"
							"labelText"					"Mouse Input"
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"tf_scoreboard_mouse_mode"
							"mouseinputenabled"			"0"
						}
					}
					"Scoreboard_Ping_Style"
					{
						"controlName"					"EditablePanel"
						"fieldName"						"Scoreboard_Ping_Style"
						"xpos"							"0"
						"ypos"							"4"
						"zpos"							"1"
						"wide"							"130"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionalToParent"			"1"

						"pin_to_sibling"				"Scoreboard_Mouse_Input"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"Toggle_Button"
						{
							"controlName"				"CExButton"
							"fieldName"					"Toggle_Button"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"20"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"actionsignallevel"			"6"
							"proportionalToParent"		"1"
							"paintbackground"			"0"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle tf_scoreboard_ping_as_text"
							"sound_depressed"			"UI/buttonclick.wav"
							"sound_released"			"UI/buttonclickrelease.wav"
						}
						"Setting_Checkbox"
						{
							"controlName"				"CvarToggleCheckButton"
							"fieldName"					"Setting_Checkbox"
							"xpos"						"-2"
							"ypos"						"cs-0.5"
							"zpos"						"21"
							"wide"						"f0"
							"tall"						"f0"
							"proportionalToParent"		"1"
							"font"						"ItemFontNameLarge"
							"labelText"					"Ping As Text"
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"tf_scoreboard_ping_as_text"
							"mouseinputenabled"			"0"
						}
					}
				}
			}
		}
	}
}